[workspace]
members = [
    "crates/three-amm-math",
    "crates/three-amm-vault",
    "crates/three-amm-pool",
    "crates/three-amm-router",
    "crates/consumer",
    "programs/three_amm",
    "programs/three_amm_pio",
]
resolver = "2"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
